--Paso 1 Eliminar la tabla si ya existe.

DROP TABLE IF EXISTS CLIENTES;

-- paso 2: Crear la tabla clientes

CREATE TABLE CLIENTES(
 	ID_CLIENTE NUMBER,
 	NOMBRE NVARCHAR2 (100),
 	DIRECCION NVARCHAR(100),
 	CONTACTO NUMBER,
 	TIENDA_ID NUMBER,
 	CONSTRAINT ID_CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);
