-- Eliminar tabla si es que existe
DROP TABLE IF EXISTS RESPONSABLES;

-- SE CREA LA TABLA

CREATE TABLE RESPONSABLES(
    ID_RESPONSABLE NUMBER,
    NOMBRE NVARCHAR2 (100),
    CONTACTO NUMBER,
    VETERINARIA_ID NUMBER,
    CONSTRAINT ID_RESPONSABLE_PK PRIMARY KEY (ID_RESPONSABLE)

);